inherit_gem: { rubocop-rails-omakase: rubocop.yml }
require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
    - "db/schema.rb"
    - "bin/*"
    - "node_modules/**/*"

Layout/LineLength:
  Max: 120
